version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - alvaro-octal
  assignees:
  - alvaro-octal
  versioning-strategy: widen
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.2
    - 2.38.5
    - 2.39.0
    - 2.42.2
    - 2.43.1
    - 2.44.0
    - 2.45.1
  - dependency-name: typedoc
    versions:
    - 0.20.18
    - 0.20.20
    - 0.20.23
    - 0.20.25
    - 0.20.27
    - 0.20.28
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.35
    - 14.14.37
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: husky
    versions:
    - 5.2.0
  - dependency-name: ts-jest
    versions:
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.4
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.9
    - 17.4.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.1
  - dependency-name: "@rollup/plugin-typescript"
    versions:
    - 8.1.1
