name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Code Style
        run: npx prettier --check .
      - name: Building
        run: npm run build --if-present
      - name: Testing
        run: npm test
        env:
          CI: true
          ESIOS_API_KEY: ${{ secrets.ESIOS_API_KEY }}

  release:
    needs: build
    name: Release
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Building
        run: npm run build --if-present
      - name: Testing
        run: npm test
        env:
          CI: true
          ESIOS_API_KEY: ${{ secrets.ESIOS_API_KEY }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx -p @semantic-release/changelog -p @semantic-release/git -p @semantic-release/commit-analyzer -p conventional-changelog-eslint -p semantic-release semantic-release
